/* @macrome
 * @generatedby @bablr/macrome-generator-bablr
 * @generatedfrom ./grammar.macro.js#44cd5c6d803ea69c494531d65db6b33a5faa09cb
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import _applyDecs from "@babel/runtime/helpers/applyDecs2305";
let _initProto, _FlagsDecs, _GroupDecs, _AssertionDecs, _StartOfInputAssertionDecs, _EndOfInputAssertionDecs, _WordBoundaryAssertionDecs, _GapDecs, _CharacterDecs, _CharacterClassDecs, _CharacterClassRangeDecs, _CharacterSetDecs, _AnyCharacterSetDecs, _DigitCharacterSetDecs, _SpaceCharacterSetDecs, _WordCharacterSetDecs, _QuantifierDecs, _AnyDecs, _KeywordDecs, _PunctuatorDecs;
import { re, spam as m } from '@bablr/boot';
import { Node, CoveredBy, InjectFrom, UndefinedAttributes, AllowEmpty, Literal } from '@bablr/helpers/decorators';
import objectEntries from 'iter-tools-es/methods/object-entries';
import * as Shared from '@bablr/helpers/productions';
import { eat, eatMatch, match, shiftMatch, guard, defineAttribute, fail, o } from '@bablr/helpers/grammar';
import { buildString, buildBoolean } from '@bablr/helpers/builders';
export const canonicalURL = 'https://bablr.org/languages/core/en/bablr-regex-pattern';
export const dependencies = {};
const escapables = new Map(objectEntries({
  n: '\n',
  r: '\r',
  t: '\t',
  0: '\0'
}));
const flagCharacters = {
  global: 'g',
  ignoreCase: 'i',
  multiline: 'm',
  dotAll: 's',
  unicode: 'u',
  sticky: 'y'
};
const unique = flags => flags.length === new Set(flags).size;
const getSpecialPattern = span => {
  if (span === 'Pattern') {
    return re`/[*+?{}[\]().^$|\n\\<>]/`;
  } else if (span === 'CharacterClass') {
    return re`/[\]\\]/`;
  } else {
    throw new Error('unknown span type for special pattern');
  }
};
export const grammar = class RegexGrammar {
  static {
    [_initProto] = _applyDecs(this, [[Node, 2, "Pattern"], [_FlagsDecs, 2, "Flags"], [AllowEmpty, 2, "Alternatives"], [[AllowEmpty, Node], 2, "Alternative"], [AllowEmpty, 2, "Elements"], [_GroupDecs, 2, "Group"], [Node, 2, "CapturingGroup"], [_AssertionDecs, 2, "Assertion"], [_StartOfInputAssertionDecs, 2, "StartOfInputAssertion"], [_EndOfInputAssertionDecs, 2, "EndOfInputAssertion"], [_WordBoundaryAssertionDecs, 2, "WordBoundaryAssertion"], [_GapDecs, 2, "Gap"], [_CharacterDecs, 2, "Character"], [_CharacterClassDecs, 2, "CharacterClass"], [_CharacterClassRangeDecs, 2, "CharacterClassRange"], [_CharacterSetDecs, 2, "CharacterSet"], [_AnyCharacterSetDecs, 2, "AnyCharacterSet"], [_DigitCharacterSetDecs, 2, "DigitCharacterSet"], [_SpaceCharacterSetDecs, 2, "SpaceCharacterSet"], [_WordCharacterSetDecs, 2, "WordCharacterSet"], [_QuantifierDecs, 2, "Quantifier"], [Node, 2, "UnsignedInteger"], [Node, 2, "UnsignedHexInteger"], [Node, 2, "EscapeSequence"], [Node, 2, "EscapeCode"], [Node, 2, "Digit"], [_AnyDecs, 2, "Any"], [_KeywordDecs, 2, "Keyword"], [_PunctuatorDecs, 2, "Punctuator"]], []).e;
  }
  constructor() {
    _initProto(this);
  }
  *[(_FlagsDecs = [UndefinedAttributes(Object.keys(flagCharacters)), AllowEmpty, Node], _GroupDecs = [CoveredBy('Element'), Node], _AssertionDecs = CoveredBy('Element'), _StartOfInputAssertionDecs = [CoveredBy('Assertion'), Node], _EndOfInputAssertionDecs = [CoveredBy('Assertion'), Node], _WordBoundaryAssertionDecs = [UndefinedAttributes(['negate']), CoveredBy('Assertion'), Node], _GapDecs = [CoveredBy('Assertion'), Node], _CharacterDecs = [CoveredBy('Element'), CoveredBy('CharacterClassElement'), Node], _CharacterClassDecs = [UndefinedAttributes(['negate']), CoveredBy('Element'), Node], _CharacterClassRangeDecs = [CoveredBy('CharacterClassElement'), Node], _CharacterSetDecs = CoveredBy('Element'), _AnyCharacterSetDecs = [CoveredBy('Element'), CoveredBy('CharacterSet'), Node], _DigitCharacterSetDecs = [UndefinedAttributes(['negate']), CoveredBy('Element'), CoveredBy('CharacterSet'), Node], _SpaceCharacterSetDecs = [UndefinedAttributes(['negate']), CoveredBy('Element'), CoveredBy('CharacterSet'), Node], _WordCharacterSetDecs = [UndefinedAttributes(['negate']), CoveredBy('Element'), CoveredBy('CharacterSet'), Node], _QuantifierDecs = [UndefinedAttributes(['min', 'max']), Node], _AnyDecs = InjectFrom(Shared), _KeywordDecs = [Literal, Node, InjectFrom(Shared)], _PunctuatorDecs = [Literal, Node, InjectFrom(Shared)], "Pattern")]() {
    yield eat(m`openToken: <*Punctuator '/' { balanced: '/', balancedSpan: 'Pattern' } />`);
    yield eat(m`<_Alternatives />`);
    yield eat(m`closeToken: <*Punctuator '/' { balancer: true } />`);
    yield eat(m`flags$: <Flags />`);
  }
  *Flags({
    ctx
  }) {
    const flags = yield match(re`/[gimsuy]+/`);
    const flagsStr = ctx.sourceTextFor(flags) || '';
    if (flagsStr && !unique(flagsStr)) throw new Error('flags must be unique');
    for (const {
      0: name,
      1: chr
    } of Object.entries(flagCharacters)) {
      if (flagsStr.includes(chr)) {
        yield defineAttribute(name, true);
      } else {
        yield defineAttribute(name, false);
      }
    }
    for (const flagChr of flagsStr) {
      yield eat(m`tokens[]: <*Keyword ${buildString(flagChr)} />`);
    }
  }
  *Alternatives() {
    do {
      yield eat(m`alternatives[]$: <Alternative />`);
    } while (yield eatMatch(m`separatorTokens[]: <*Punctuator '|' />`));
  }
  *Alternative() {
    yield eat(m`elements[]+$: <_Elements />`);
  }
  *Elements() {
    yield eat(m`.[]: []`);
    while (yield match(re`/[^|]/`)) {
      yield eat(m`.[]+: <__Element />`);
    }
  }
  *Element() {
    yield guard(m`<*Keyword /[*+?]/ />`);
    yield eat(m`<_Any />`, [m`<CharacterClass '[' />`, m`<Group '(?:' />`, m`<_Assertion /[$^]|\\b/i />`, m`<Gap '\\g' />`, m`<_CharacterSet /\.|\\[dswp]/i />`, m`<*Character />`]);
    if (yield match(re`/[*+?{]/`)) {
      return shiftMatch(m`<Quantifier />`);
    }
  }
  *Group() {
    yield eat(m`openToken: <*Punctuator '(?:' { balanced: ')' } />`);
    yield eat(m`<_Alternatives />`);
    yield eat(m`closeToken: <*Punctuator ')' { balancer: true } />`);
  }
  *CapturingGroup() {
    yield eat(m`openToken: <*Punctuator '(' { balanced: ')' } />`);
    yield eat(m`<_Alternatives />`);
    yield eat(m`closeToken: <*Punctuator ')' { balancer: true } />`);
  }
  *Assertion() {
    yield eat(m`<_Any />`, [m`<*StartOfInputAssertion '^' />`, m`<*EndOfInputAssertion '$' />`, m`<*WordBoundaryAssertion /\\b/i />`]);
  }
  *StartOfInputAssertion() {
    yield eat(m`sigilToken: <*Keyword '^' />`);
  }
  *EndOfInputAssertion() {
    yield eatMatch(m`sigilToken: <*Keyword '$' />`);
  }
  *WordBoundaryAssertion({
    ctx
  }) {
    yield eatMatch(m`escapeToken: <*Punctuator '\\' />`);
    const m_ = yield eat(m`value: <*Keyword /b/i />`);
    yield defineAttribute('negate', buildBoolean(ctx.sourceTextFor(m_) === 'B'));
  }
  *Gap() {
    yield eatMatch(m`escapeToken: <*Punctuator '\\' />`);
    yield eat(m`value: <*Keyword 'g' />`);
  }
  *Character() {
    if (yield match('\\')) {
      yield eat(m`@: <EscapeSequence />`);
    } else {
      yield eat(re`/[^\r\n\t]/`);
    }
  }
  *CharacterClass() {
    yield eat(m`openToken: <*Punctuator '[' { balancedSpan: 'CharacterClass', balanced: ']' } />`);
    let negate = yield eatMatch(m`negateToken: <*Keyword '^' />`, null, o({
      bind: true
    }));
    yield defineAttribute('negate', !!negate);
    while (yield match(re`/./s`)) {
      yield eat(m`elements[]+$: <__CharacterClassElement />`);
    }
    yield eat(m`closeToken: <*Punctuator ']' { balancer: true } />`);
  }
  *CharacterClassElement() {
    yield eat(m`<_Any />`, [m`<_CharacterSet /\\[dswp]/i />`, m`<Gap '\\g' />`, m`<*Character />`]);
    if (yield match('-')) {
      return shiftMatch(m`<CharacterClassRange />`);
    }
  }
  *CharacterClassRange() {
    yield eat(m`min+$: <*Character />`);
    yield eat(m`sigilToken: <*Punctuator '-' />`);
    yield eat(m`max+$: <*Character />`);
  }
  *CharacterSet() {
    yield eat(m`<_Any />`, [m`<AnyCharacterSet '.' />`, m`<DigitCharacterSet /\\[dD]/  />`, m`<SpaceCharacterSet /\\[sS]/  />`, m`<WordCharacterSet /\\[wW]/  />`]);
  }
  *AnyCharacterSet() {
    yield eat(m`sigilToken: <*Keyword '.' />`);
  }
  *DigitCharacterSet({
    ctx
  }) {
    yield eat(m`escapeToken: <*Punctuator '\\' />`);
    let code = yield eat(m`value: <*Keyword /[dD]/ />`);
    yield defineAttribute('negate', ctx.sourceTextFor(code) === 'D');
  }
  *SpaceCharacterSet({
    ctx
  }) {
    yield eat(m`escapeToken: <*Punctuator '\\' />`);
    let code = yield eat(m`value: <*Keyword /[sS]/ />`);
    yield defineAttribute('negate', ctx.sourceTextFor(code) === 'S');
  }
  *WordCharacterSet({
    ctx
  }) {
    yield eat(m`escapeToken: <*Punctuator '\\' />`);
    let code = yield eat(m`value: <*Keyword /[wW]/ />`);
    yield defineAttribute('negate', ctx.sourceTextFor(code) === 'W');
  }
  *Quantifier({
    ctx
  }) {
    yield eat(m`element+$: <__Element />`);
    let attrs, sigil;
    if (sigil = yield eatMatch(m`sigilToken: <*Keyword /[*+?]/ />`)) {
      switch (ctx.sourceTextFor(sigil)) {
        case '*':
          attrs = {
            min: 0,
            max: Infinity
          };
          break;
        case '+':
          attrs = {
            min: 1,
            max: Infinity
          };
          break;
        case '?':
          attrs = {
            min: 0,
            max: 1
          };
          break;
        default:
          yield fail();
      }
    } else if (yield eat(m`openToken: <*Punctuator '{' { balanced: '}' } />`)) {
      let max;
      let min = yield eat(m`min$: <*UnsignedInteger />`);
      if (yield eatMatch(m`separator: <*Punctuator ',' />`)) {
        max = yield eatMatch(m`max$: <*UnsignedInteger />`);
      }
      min = min && ctx.sourceTextFor(min);
      max = max && ctx.sourceTextFor(max);
      min = min && parseInt(min, 10);
      max = max && parseInt(max, 10);
      attrs = {
        min,
        max
      };
      yield eat(m`closeToken: <*Punctuator '}' { balancer: true } />`);
    }
    yield defineAttribute('min', attrs.min);
    yield defineAttribute('max', attrs.max);
  }
  *UnsignedInteger() {
    yield eat(re`/\d+/`);
  }
  *UnsignedHexInteger() {
    yield eat(re`/[\da-fA-F]+/`);
  }
  *EscapeSequence({
    state,
    ctx
  }) {
    const parentSpan = state.span;
    yield eat(m`escape: <*Punctuator '\\' { openSpan: 'Escape' } />`);
    let m_;
    let cooked;
    if (m_ = yield match(re`/[\\/nrt0]/`)) {
      const match_ = ctx.sourceTextFor(m_);
      yield eat(m`code: <*Keyword ${buildString(match_)} { closeSpan: 'Escape' } />`);
      cooked = escapables.get(match_) || match_;
    } else if (m_ = yield match(getSpecialPattern(parentSpan))) {
      cooked = ctx.sourceTextFor(m_);
      yield eat(m`code: <*Keyword ${buildString(cooked)} { closeSpan: 'Escape' } />`);
    } else if (yield match(re`/[ux]/`)) {
      let code = yield eat(m`code: <EscapeCode { closeSpan: 'Escape' } />`);
      let value = code.get('value');
      cooked = String.fromCodePoint(parseInt(ctx.sourceTextFor(value), 16));
    } else {
      yield fail();
    }
    yield defineAttribute('cooked', cooked);
  }
  *EscapeCode() {
    if (yield eatMatch(m`type: <*Keyword 'u' />`)) {
      if (yield eatMatch(m`openToken: <*Punctuator '{' />`)) {
        yield eatMatch(m`value$: <*UnsignedHexInteger />`);
        yield eat(m`closeToken: <*Punctuator '}' />`);
      } else {
        yield eat(m`value$: <*UnsignedHexInteger /[\da-fA-F]{4}/ />`);
        yield eat(m`closeToken: null`);
      }
    } else if (yield eatMatch(m`type: <*Keyword 'x' />`)) {
      yield eat(m`openToken: null`);
      yield eat(m`value$: <*UnsignedHexInteger /[\da-fA-F]{2}/ />`);
      yield eat(m`closeToken: null`);
    }
  }
  *Digits() {
    while (yield eatMatch(m`<*Digit />`));
  }
  *Digit() {
    yield eat(re`/\d/`);
  }
  *Any() {}
  *Keyword() {}
  *Punctuator() {}
};